#This is using the offical image as the parent image
FROM httpd:2.4

#We are setting the working directory here
WORKDIR /usr/local/apache2/htdocs/

#We are now copying the current directory contents into the container at /usr/local/apache2/htdocs/
COPY . /usr/local/apache2/htdocs/